# Copyright (c) The Kowabunga Project
# Apache License, Version 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0.txt)
# SPDX-License-Identifier: Apache-2.0

APP_DESCRIPTION = '''
NFS Ganesha Export REST API Server
'''

NFS_BLOCK_EXPORT = 'EXPORT'
NFS_EXPORT_ATTR_ID = 'Export_id'
NFS_EXPORT_ATTR_PATH = 'Path'
NFS_EXPORT_ATTR_PSEUDO = 'Pseudo'
NFS_EXPORT_ATTR_ACCESS_TYPE = 'Access_Type'
NFS_EXPORT_ATTR_ACCESS_TYPE_ALLOWED_VALUES = ['RO', 'RW']
NFS_EXPORT_ATTR_PROTOCOLS = 'Protocols'
NFS_EXPORT_ATTR_PROTOCOLS_ALLOWED_VALUES = [3, 4]
NFS_EXPORT_ATTR_TRANSPORTS = 'Transports'
NFS_EXPORT_ATTR_TRANSPORTS_DEFAULT_VALUE = 'TCP'
NFS_EXPORT_ATTR_SEC_TYPE = 'SecType'
NFS_EXPORT_ATTR_SEC_TYPE_DEFAULT_VALUE = 'sys'
NFS_EXPORT_ATTR_SQUASH = 'Squash'
NFS_EXPORT_ATTR_SQUASH_DEFAULT_VALUE = 'No_Root_Squash'
NFS_EXPORT_ATTR_EXPIRE = 'Attr_Expiration_Time'
NFS_EXPORT_ATTR_EXPIRE_DEFAULT_VALUE = 0
NFS_BLOCK_FSAL = 'FSAL'
NFS_FSAL_ATTR_NAME = 'Name'
NFS_FSAL_ATTR_NAME_DEFAULT_VALUE = 'CEPH'
NFS_FSAL_ATTR_USER = 'User_Id'
NFS_FSAL_ATTR_USER_DEFAULT_VALUE = 'admin'
NFS_FSAL_ATTR_FS = 'Filesystem'
NFS_FSAL_ATTR_FS_DEFAULT_VALUE = 'nfs'
NFS_BLOCK_CLIENT = 'CLIENT'
NFS_CLIENT_ATTR_CLIENTS = 'Clients'
