name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Install build requirements
      run: sudo apt-get -y install devscripts debhelper
    - name: Build Debian package
      run: ./debian.sh
    - name: Release Debian Package
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ../*.deb
    - name: Trigger APT repository update
      uses: peter-evans/repository-dispatch@v3
      with:
        token: '${{ secrets.PAT_PACKAGES_WORKFLOW_TOKEN }}'
        repository: kowabunga-cloud/packages
        event-type: Publish-Deb
